use_frameworks!

platform :ios, '9.0'

target 'HMMessageKit_Example' do
  pod 'HMMessageKit', :path => '../'

  target 'HMMessageKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
